version: "3.9"

services:
  db:
    image: postgres:13.6
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER:-user}
      - POSTGRES_PASSWORD=${DB_PASS:-pass}
      - POSTGRES_DB=${DB_NAME:-boilerplate-db}
    ports:
      - "5432:5432"
